export const employerSizeOptions: Record<string, { low: number | null, high: number | null }> = {
  "< 10": { low: null, high: 9 },
  "10-49": { low: 10, high: 49 },
  "50-99": { low: 50, high: 99 },
  "100-249": { low: 100, high: 249 },
  "250-499": { low: 250, high: 499 },
  "500-999": { low: 500, high: 999 },
  "1,000-9,999": { low: 1000, high: 9999 },
  "10,000+": { low: 10000, high: null }
};

export const industries = [
  "Academia & Research",
  "Aerospace & Aviation",
  "Agriculture",
  "Automotive",
  "Business & Management",
  "Chemical & Materials Sciences",
  "Commerce & Retail",
  "Construction & Maintenance",
  "Criminal Justice",
  "Education",
  "Electrical, HVAC & Plumbing",
  "Emergency & Public Services",
  "Energy & Utilities",
  "Engineering",
  "Entertainment & Media",
  "Environmental & Earth Sciences",
  "Fashion",
  "Finance",
  "Fine Arts & Culture",
  "Food & Beverage",
  "Government & Public Administration",
  "History & Anthropology",
  "Healthcare & Medicine",
  "Hospitality & Tourism",
  "Language & Linguistics",
  "Law",
  "Life & Biomedical Sciences",
  "Literature & Writing",
  "Logistics & Supply Chain",
  "Manufacturing & Production",
  "Military & Defense",
  "Music",
  "News & Publishing",
  "Nonprofit & NGOs",
  "Philosophy & Ethics",
  "Photography & Videography",
  "Real Estate",
  "Religion & Spirituality",
  "Sales & Marketing",
  "Social Services",
  "Sports, Wellness & Fitness",
  "Tech",
  "Telecommunications",
  "Transportation"
] as const;

export const months = [
  "January", 
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December"
];